apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app          # ✅ Deployment name (can be anything)
  labels:
    app: flask-app         # ✅ Label (must match Service selector below)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app       # ✅ Must match template.metadata.labels
  template:
    metadata:
      labels:
        app: flask-app     # ✅ Must match Service selector
    spec:
      containers:
      - name: flask-app    # ✅ Container name (can be anything)
        image: 020866158197.dkr.ecr.us-east-1.amazonaws.com/sentiment-repo:latest  # ⬅ MUST match your ECR repo + tag
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret  # ✅ Must match your Secret resource
              key: CAPSTONE_TEST     # ✅ Must exist as a key in the Secret

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service  # ✅ Service name (can be anything)
spec:
  type: LoadBalancer
  selector:
    app: flask-app         # ✅ Must match Deployment’s Pod labels
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
